-- NOTE: This file is auto generated by ./sql-generator

-- AlbumRepository.getById
with
  "album_user" as (
    select
      *
    from
      "album_user"
    where
      "album_user"."albumId" = $1
  )
select
  "album".*,
  (
    select
      coalesce(json_agg(agg), '[]')
    from
      (
        select
          "album_user"."role",
          (
            select
              to_json(obj)
            from
              (
                select
                  "id",
                  "name",
                  "email",
                  "avatarColor",
                  "profileImagePath",
                  "profileChangedAt"
                from
                  (
                    select
                      1
                  ) as "dummy"
              ) as obj
          ) as "user"
        from
          "album_user"
          inner join "user" on "user"."id" = "album_user"."userId"
        where
          "album_user"."albumId" = "album"."id"
        order by
          "album_user"."role",
          "album_user"."userId" = $2 desc,
          "user"."name" asc
      ) as agg
  ) as "albumUsers",
  (
    select
      coalesce(json_agg(agg), '[]')
    from
      (
        select
          "shared_link".*
        from
          "shared_link"
        where
          "shared_link"."albumId" = "album"."id"
      ) as agg
  ) as "sharedLinks",
  (
    select
      json_agg("asset") as "assets"
    from
      (
        select
          "asset".*,
          "asset_exif" as "exifInfo"
        from
          "asset"
          left join "asset_exif" on "asset"."id" = "asset_exif"."assetId"
          inner join "album_asset" on "album_asset"."assetId" = "asset"."id"
        where
          "album_asset"."albumId" = "album"."id"
          and "asset"."deletedAt" is null
          and (
            "album_asset"."sourceLibraryId" is null
            or exists (
              select
              from
                "asset"
                inner join "library" on "library"."id" = "asset"."libraryId"
                and "library"."deletedAt" is null
                inner join "user" as "owner" on "owner"."id" = "library"."ownerId"
                and "owner"."deletedAt" is null
                left join "library_user" on "library_user"."libraryId" = "library"."id"
                and "library_user"."userId" = $3
              where
                "asset"."id" = "album_asset"."assetId"
                and "library"."id" = "album_asset"."sourceLibraryId"
                and "asset"."deletedAt" is null
                and "asset"."visibility" = 'timeline'
                and (
                  "library"."ownerId" = $4
                  or "library_user"."userId" is not null
                )
            )
          )
          and "asset"."visibility" in ('archive', 'timeline')
        order by
          "asset"."fileCreatedAt" desc
      ) as "asset"
  ) as "assets"
from
  "album"
where
  "album"."id" = $5
  and "album"."deletedAt" is null

-- AlbumRepository.getByAssetId
select
  "album".*,
  (
    select
      coalesce(json_agg(agg), '[]')
    from
      (
        select
          "album_user"."role",
          (
            select
              to_json(obj)
            from
              (
                select
                  "id",
                  "name",
                  "email",
                  "avatarColor",
                  "profileImagePath",
                  "profileChangedAt"
                from
                  (
                    select
                      1
                  ) as "dummy"
              ) as obj
          ) as "user"
        from
          "album_user"
          inner join "user" on "user"."id" = "album_user"."userId"
        where
          "album_user"."albumId" = "album"."id"
        order by
          "album_user"."role",
          "album_user"."userId" = $1 desc,
          "user"."name" asc
      ) as agg
  ) as "albumUsers"
from
  "album"
  inner join "album_asset" on "album_asset"."albumId" = "album"."id"
where
  exists (
    select
    from
      "album_user"
    where
      "album_user"."albumId" = "album"."id"
      and "album_user"."userId" = $2
  )
  and "album_asset"."assetId" = $3
  and "album"."deletedAt" is null
  and (
    "album_asset"."sourceLibraryId" is null
    or exists (
      select
      from
        "asset"
        inner join "library" on "library"."id" = "asset"."libraryId"
        and "library"."deletedAt" is null
        inner join "user" as "owner" on "owner"."id" = "library"."ownerId"
        and "owner"."deletedAt" is null
        left join "library_user" on "library_user"."libraryId" = "library"."id"
        and "library_user"."userId" = $4
      where
        "asset"."id" = "album_asset"."assetId"
        and "library"."id" = "album_asset"."sourceLibraryId"
        and "asset"."deletedAt" is null
        and "asset"."visibility" = 'timeline'
        and (
          "library"."ownerId" = $5
          or "library_user"."userId" is not null
        )
    )
  )
order by
  "album"."createdAt" desc

-- AlbumRepository.getByAssetIds
select
  "album"."id",
  "album_asset"."assetId"
from
  "album"
  inner join "album_asset" on "album_asset"."albumId" = "album"."id"
where
  exists (
    select
    from
      "album_user"
    where
      "album_user"."albumId" = "album"."id"
      and "album_user"."userId" = $1
  )
  and "album_asset"."assetId" in ($2)
  and "album"."deletedAt" is null
  and (
    "album_asset"."sourceLibraryId" is null
    or exists (
      select
      from
        "asset"
        inner join "library" on "library"."id" = "asset"."libraryId"
        and "library"."deletedAt" is null
        inner join "user" as "owner" on "owner"."id" = "library"."ownerId"
        and "owner"."deletedAt" is null
        left join "library_user" on "library_user"."libraryId" = "library"."id"
        and "library_user"."userId" = $3
      where
        "asset"."id" = "album_asset"."assetId"
        and "library"."id" = "album_asset"."sourceLibraryId"
        and "asset"."deletedAt" is null
        and "asset"."visibility" = 'timeline'
        and (
          "library"."ownerId" = $4
          or "library_user"."userId" is not null
        )
    )
  )

-- AlbumRepository.getMetadataForIds
select
  "album_asset"."albumId" as "albumId",
  min(
    ("asset"."localDateTime" AT TIME ZONE 'UTC'::text)::date
  ) as "startDate",
  max(
    ("asset"."localDateTime" AT TIME ZONE 'UTC'::text)::date
  ) as "endDate",
  max("asset"."updatedAt") as "lastModifiedAssetTimestamp",
  count("asset"."id")::int as "assetCount"
from
  "asset"
  inner join "album_asset" on "album_asset"."assetId" = "asset"."id"
where
  "asset"."visibility" in ('archive', 'timeline')
  and "album_asset"."albumId" in ($1)
  and "asset"."deletedAt" is null
  and (
    "album_asset"."sourceLibraryId" is null
    or exists (
      select
      from
        "asset"
        inner join "library" on "library"."id" = "asset"."libraryId"
        and "library"."deletedAt" is null
        inner join "user" as "owner" on "owner"."id" = "library"."ownerId"
        and "owner"."deletedAt" is null
        left join "library_user" on "library_user"."libraryId" = "library"."id"
        and "library_user"."userId" = $2
      where
        "asset"."id" = "album_asset"."assetId"
        and "library"."id" = "album_asset"."sourceLibraryId"
        and "asset"."deletedAt" is null
        and "asset"."visibility" = 'timeline'
        and (
          "library"."ownerId" = $3
          or "library_user"."userId" is not null
        )
    )
  )
group by
  "album_asset"."albumId"

-- AlbumRepository.getAll
select
  "album".*,
  (
    select
      coalesce(json_agg(agg), '[]')
    from
      (
        select
          "album_user"."role",
          (
            select
              to_json(obj)
            from
              (
                select
                  "id",
                  "name",
                  "email",
                  "avatarColor",
                  "profileImagePath",
                  "profileChangedAt"
                from
                  (
                    select
                      1
                  ) as "dummy"
              ) as obj
          ) as "user"
        from
          "album_user"
          inner join "user" on "user"."id" = "album_user"."userId"
        where
          "album_user"."albumId" = "album"."id"
        order by
          "album_user"."role",
          "album_user"."userId" = $1 desc,
          "user"."name" asc
      ) as agg
  ) as "albumUsers",
  (
    select
      coalesce(json_agg(agg), '[]')
    from
      (
        select
          "shared_link".*
        from
          "shared_link"
        where
          "shared_link"."albumId" = "album"."id"
      ) as agg
  ) as "sharedLinks"
from
  "album"
  inner join "album_user" on "album_user"."albumId" = "album"."id"
  and "album_user"."userId" = $2
where
  "album"."deletedAt" is null
  and "album_user"."role" = 'owner'
  and (
    exists (
      select
      from
        "album_user" as "au"
      where
        "au"."albumId" = "album"."id"
        and "au"."role" != 'owner'
    )
    or exists (
      select
      from
        "shared_link"
      where
        "shared_link"."albumId" = "album"."id"
    )
  )
order by
  "album"."createdAt" desc

-- AlbumRepository.getAllIds
select
  "album"."id"
from
  "album"
  inner join "album_user" on "album_user"."albumId" = "album"."id"
  and "album_user"."userId" = $1
where
  "album"."deletedAt" is null
  and "album_user"."role" = 'owner'
  and (
    exists (
      select
      from
        "album_user" as "au"
      where
        "au"."albumId" = "album"."id"
        and "au"."role" != 'owner'
    )
    or exists (
      select
      from
        "shared_link"
      where
        "shared_link"."albumId" = "album"."id"
    )
  )
order by
  "album"."createdAt" desc

-- AlbumRepository.removeAssetsFromAll
delete from "album_asset"
where
  "album_asset"."assetId" in ($1)

-- AlbumRepository.getAssetIds
select
  *
from
  "album_asset"
where
  "album_asset"."albumId" = $1
  and "album_asset"."assetId" in ($2)

-- AlbumRepository.addAssetIds
insert into
  "album_asset"
select
  $1::uuid as "albumId",
  unnest($2::uuid[]) as "assetId"
from
  (
    select
      1
  ) as "dummy"
on conflict ("albumId", "assetId") do update
set
  "sourceLibraryId" = $3

-- AlbumRepository.addLibraryAssetIds
insert into
  "album_asset" ("albumId", "assetId", "sourceLibraryId")
values
  ($1, $2, $3)
on conflict ("albumId", "assetId") do nothing

-- AlbumRepository.create
with
  "album" as (
    insert into
      "album" ("albumName")
    values
      ($1)
    returning
      *
  ),
  "album_user" as (
    insert into
      "album_user" ("albumId", "userId", "role")
    select
      "album"."id" as "albumId",
      unnest($2::uuid[]) as "userId",
      unnest($3::album_user_role_enum[]) as "role"
    from
      "album"
    returning
      "album_user"."albumId",
      "album_user"."userId",
      "album_user"."role"
  ),
  "album_asset" as (
    insert into
      "album_asset" ("albumId", "assetId", "sourceLibraryId")
    select
      "album"."id" as "albumId",
      unnest($4::uuid[]) as "assetId",
      unnest($5::uuid[]) as "sourceLibraryId"
    from
      "album"
    on conflict do nothing
    returning
      "album_asset"."albumId",
      "album_asset"."assetId",
      "album_asset"."sourceLibraryId"
  )
select
  "album".*,
  (
    select
      coalesce(json_agg(agg), '[]')
    from
      (
        select
          "album_user"."role",
          (
            select
              to_json(obj)
            from
              (
                select
                  "id",
                  "name",
                  "email",
                  "avatarColor",
                  "profileImagePath",
                  "profileChangedAt"
                from
                  (
                    select
                      1
                  ) as "dummy"
              ) as obj
          ) as "user"
        from
          "album_user"
          inner join "user" on "user"."id" = "album_user"."userId"
        where
          "album_user"."albumId" = "album"."id"
        order by
          "album_user"."role",
          "user"."name" asc
      ) as agg
  ) as "albumUsers",
  (
    select
      json_agg("asset") as "assets"
    from
      (
        select
          "asset".*,
          "asset_exif" as "exifInfo"
        from
          "asset"
          left join "asset_exif" on "asset"."id" = "asset_exif"."assetId"
          inner join "album_asset" on "album_asset"."assetId" = "asset"."id"
        where
          "album_asset"."albumId" = "album"."id"
          and "asset"."deletedAt" is null
          and (
            "album_asset"."sourceLibraryId" is null
            or false
          )
          and "asset"."visibility" in ('archive', 'timeline')
        order by
          "asset"."fileCreatedAt" desc
      ) as "asset"
  ) as "assets"
from
  "album"

-- AlbumRepository.getContributorCounts
select
  "asset"."ownerId" as "userId",
  count(*) as "assetCount"
from
  "album_asset"
  inner join "asset" on "asset"."id" = "assetId"
where
  "asset"."deletedAt" is null
  and "album_asset"."albumId" = $1
  and (
    "album_asset"."sourceLibraryId" is null
    or exists (
      select
      from
        "asset"
        inner join "library" on "library"."id" = "asset"."libraryId"
        and "library"."deletedAt" is null
        inner join "user" as "owner" on "owner"."id" = "library"."ownerId"
        and "owner"."deletedAt" is null
        left join "library_user" on "library_user"."libraryId" = "library"."id"
        and "library_user"."userId" = $2
      where
        "asset"."id" = "album_asset"."assetId"
        and "library"."id" = "album_asset"."sourceLibraryId"
        and "asset"."deletedAt" is null
        and "asset"."visibility" = 'timeline'
        and (
          "library"."ownerId" = $3
          or "library_user"."userId" is not null
        )
    )
  )
group by
  "asset"."ownerId"
order by
  "assetCount" desc

-- AlbumRepository.hasProvenanceAssets
select
  "assetId"
from
  "album_asset"
where
  "albumId" = $1
  and "sourceLibraryId" is not null
limit
  $2

-- AlbumRepository.copyAlbums
insert into
  "album_asset" ("albumId", "assetId", "sourceLibraryId")
select
  "album_asset"."albumId",
  $1 as "assetId",
  "album_asset"."sourceLibraryId"
from
  "album_asset"
where
  "album_asset"."assetId" = $2
on conflict do nothing
