-- NOTE: This file is auto generated by ./sql-generator

-- LibraryRepository.get
select
  "library".*
from
  "library"
where
  "library"."id" = $1
  and "library"."deletedAt" is null

-- LibraryRepository.getAll
select
  "library".*
from
  "library"
where
  "library"."deletedAt" is null
order by
  "createdAt" asc

-- LibraryRepository.getAllDeleted
select
  "library".*
from
  "library"
where
  "library"."deletedAt" is not null
order by
  "createdAt" asc

-- LibraryRepository.getStatistics
select
  count(*) filter (
    where
      (
        "asset"."type" = $1
        and "asset"."visibility" != $2
      )
  ) as "photos",
  count(*) filter (
    where
      (
        "asset"."type" = $3
        and "asset"."visibility" != $4
      )
  ) as "videos",
  coalesce(sum("asset_exif"."fileSizeInByte"), $5) as "usage"
from
  "library"
  inner join "asset" on "asset"."libraryId" = "library"."id"
  left join "asset_exif" on "asset_exif"."assetId" = "asset"."id"
where
  "library"."id" = $6
group by
  "library"."id"
select
  0::int as "photos",
  0::int as "videos",
  0::int as "usage",
  0::int as "total"
from
  "library"
where
  "library"."id" = $1

-- LibraryRepository.getSharedUsers
select
  "library_user".*,
  (
    select
      to_json(obj)
    from
      (
        select
          "id",
          "name",
          "email",
          "avatarColor",
          "profileImagePath",
          "profileChangedAt"
        from
          "user"
        where
          "user"."id" = "library_user"."userId"
      ) as obj
  ) as "user"
from
  "library_user"
  inner join "user" on "user"."id" = "library_user"."userId"
  and "user"."deletedAt" is null
where
  "library_user"."libraryId" = $1

-- LibraryRepository.addUsers
insert into
  "library_user" ("libraryId", "userId", "role")
values
  ($1, $2, $3)
on conflict ("libraryId", "userId") do nothing

-- LibraryRepository.updateUserRole
update "library_user"
set
  "role" = $1
where
  "libraryId" = $2
  and "userId" = $3
returning
  *

-- LibraryRepository.getUserShare
select
  *
from
  "library_user"
where
  "libraryId" = $1
  and "userId" = $2

-- LibraryRepository.updateUser
update "library_user"
set
  "inTimeline" = $1
where
  "libraryId" = $2
  and "userId" = $3
returning
  *

-- LibraryRepository.updateMyShare
update "library_user"
set
  "inTimeline" = $1,
  "timelineEnabledId" = case
    when "inTimeline" = $2 then immich_uuid_v7 ()
    else "timelineEnabledId"
  end
where
  "libraryId" = $3
  and "userId" = $4
returning
  *

-- LibraryRepository.removeUser
delete from "library_user"
where
  "libraryId" = $1
  and "userId" = $2

-- LibraryRepository.getOwned
select
  "library".*
from
  "library"
where
  "library"."ownerId" = $1
  and "library"."deletedAt" is null
order by
  "createdAt" asc

-- LibraryRepository.getSharedWithUser
select
  "library".*,
  "library_user"."role",
  "library_user"."inTimeline",
  (
    select
      to_json(obj)
    from
      (
        select
          "id",
          "name",
          "email",
          "avatarColor",
          "profileImagePath",
          "profileChangedAt"
        from
          "user"
        where
          "user"."id" = "library"."ownerId"
      ) as obj
  ) as "owner",
  (
    select
      count(*) as "count"
    from
      "asset"
    where
      "asset"."libraryId" = "library"."id"
      and "asset"."deletedAt" is null
      and "asset"."visibility" = 'timeline'
  ) as "assetCount"
from
  "library_user"
  inner join "library" on "library"."id" = "library_user"."libraryId"
  and "library"."deletedAt" is null
  inner join "user" as "owner" on "owner"."id" = "library"."ownerId"
  and "owner"."deletedAt" is null
where
  "library_user"."userId" = $1
order by
  "library"."createdAt" asc

-- LibraryRepository.getInTimelineSharedLibraryIds
select
  "library"."id"
from
  "library_user"
  inner join "library" on "library"."id" = "library_user"."libraryId"
  and "library"."deletedAt" is null
  inner join "user" as "owner" on "owner"."id" = "library"."ownerId"
  and "owner"."deletedAt" is null
where
  "library_user"."userId" = $1
  and "library_user"."inTimeline" = $2
